GITHUB_TOKEN_ENV = "GITHUB_TOKEN"  # noqa: S105
INPUT_ORGANIZATIONS_ENV = "INPUT_ORGANIZATIONS"
INPUT_REPOSITORIES_ENV = "INPUT_REPOSITORIES"

INPUT_OUTPUT_PATH_ENV = "INPUT_OUTPUT_PATH"
INPUT_OUTPUT_FILENAME_ENV = "INPUT_OUTPUT_FILENAME"
HTTP_REQUEST_TIMEOUT = 30

INPUT_PYPI_PACKAGES_ENV = "INPUT_PYPI_PACKAGES"
PYPI_OUTPUT_FILENAME_ENV = "INPUT_PYPI_OUTPUT_FILENAME"
